
/*	____________________________________________________________________________
  |																			    |
  | Module: Port 														    	|
  |																			    |
  | File Name: Port_PBcfg.c													    |
  |																			    |
  | Description: Post Build Configuration Source file for TM4C123GH6PM          |
  | Microcontroller - Port Driver						        				|
  |																			    |
  | Author: Youssif Hossam													    |
  |_____________________________________________________________________________|
*/

#include "Port.h"

/*
 * Module Version 1.0.0
 */
#define PORT_PBCFG_SW_MAJOR_VERSION              (1U)
#define PORT_PBCFG_SW_MINOR_VERSION              (0U)
#define PORT_PBCFG_SW_PATCH_VERSION              (0U)

/*
 * AUTOSAR Version 4.0.3
 */
#define PORT_PBCFG_AR_RELEASE_MAJOR_VERSION     (4U)
#define PORT_PBCFG_AR_RELEASE_MINOR_VERSION     (0U)
#define PORT_PBCFG_AR_RELEASE_PATCH_VERSION     (3U)

/* AUTOSAR Version checking between Port_PBcfg.c and Dio.h files */
#if ((PORT_PBCFG_AR_RELEASE_MAJOR_VERSION != PORT_AR_RELEASE_MAJOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_MINOR_VERSION != PORT_AR_RELEASE_MINOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_PATCH_VERSION != PORT_AR_RELEASE_PATCH_VERSION))
  #error "The AR version of PBcfg.c does not match the expected version"
#endif

/* Software Version checking between Port_PBcfg.c and Dio.h files */
#if ((PORT_PBCFG_SW_MAJOR_VERSION != PORT_SW_MAJOR_VERSION)\
 ||  (PORT_PBCFG_SW_MINOR_VERSION != PORT_SW_MINOR_VERSION)\
 ||  (PORT_PBCFG_SW_PATCH_VERSION != PORT_SW_PATCH_VERSION))
  #error "The SW version of PBcfg.c does not match the expected version"
#endif

/* PB structure used with Port_Init API */
const Port_ConfigType Port_Configuration =
{
 {
  {
   PortPin_A0_ID, PORT_PIN_IN, STD_LOW, PORT_DIGITAL, PORT_MODE_GPIO, STD_OFF, STD_OFF, PORT_RESISTOR_OFF
  },
  {
   PortPin_A1_ID, PORT_PIN_IN, STD_LOW, PORT_DIGITAL, PORT_MODE_GPIO, STD_OFF, STD_OFF, PORT_RESISTOR_OFF
  },
  {
   PortPin_A2_ID, PORT_PIN_IN, STD_LOW, PORT_DIGITAL, PORT_MODE_GPIO, STD_OFF, STD_OFF, PORT_RESISTOR_OFF
  },
  {
   PortPin_A3_ID, PORT_PIN_IN, STD_LOW, PORT_DIGITAL, PORT_MODE_GPIO, STD_OFF, STD_OFF, PORT_RESISTOR_OFF
  },
  {
   PortPin_A4_ID, PORT_PIN_IN, STD_LOW, PORT_DIGITAL, PORT_MODE_GPIO, STD_OFF, STD_OFF, PORT_RESISTOR_OFF
  },
  {
   PortPin_A5_ID, PORT_PIN_IN, STD_LOW, PORT_DIGITAL, PORT_MODE_GPIO, STD_OFF, STD_OFF, PORT_RESISTOR_OFF
  },
  {
   PortPin_A6_ID, PORT_PIN_IN, STD_LOW, PORT_DIGITAL, PORT_MODE_GPIO, STD_OFF, STD_OFF, PORT_RESISTOR_OFF
  },
  {
   PortPin_A7_ID, PORT_PIN_IN, STD_LOW, PORT_DIGITAL, PORT_MODE_GPIO, STD_OFF, STD_OFF, PORT_RESISTOR_OFF
  },
  {
   PortPin_B0_ID, PORT_PIN_IN, STD_LOW, PORT_DIGITAL, PORT_MODE_GPIO, STD_OFF, STD_OFF, PORT_RESISTOR_OFF
  },
  {
   PortPin_B1_ID, PORT_PIN_IN, STD_LOW, PORT_DIGITAL, PORT_MODE_GPIO, STD_OFF, STD_OFF, PORT_RESISTOR_OFF
  },
  {
   PortPin_B2_ID, PORT_PIN_IN, STD_LOW, PORT_DIGITAL, PORT_MODE_GPIO, STD_OFF, STD_OFF, PORT_RESISTOR_OFF
  },
  {
   PortPin_B3_ID, PORT_PIN_IN, STD_LOW, PORT_DIGITAL, PORT_MODE_GPIO, STD_OFF, STD_OFF, PORT_RESISTOR_OFF
  },
  {
   PortPin_B4_ID, PORT_PIN_IN, STD_LOW, PORT_DIGITAL, PORT_MODE_GPIO, STD_OFF, STD_OFF, PORT_RESISTOR_OFF
  },
  {
   PortPin_B5_ID, PORT_PIN_IN, STD_LOW, PORT_DIGITAL, PORT_MODE_GPIO, STD_OFF, STD_OFF, PORT_RESISTOR_OFF
  },
  {
   PortPin_B6_ID, PORT_PIN_IN, STD_LOW, PORT_DIGITAL, PORT_MODE_GPIO, STD_OFF, STD_OFF, PORT_RESISTOR_OFF
  },
  {
   PortPin_B7_ID, PORT_PIN_IN, STD_LOW, PORT_DIGITAL, PORT_MODE_GPIO, STD_OFF, STD_OFF, PORT_RESISTOR_OFF
  },
  {
   PortPin_C0_ID, PORT_PIN_IN, STD_LOW, PORT_DIGITAL, PORT_MODE_GPIO, STD_OFF, STD_OFF, PORT_RESISTOR_OFF
  },
  {
   PortPin_C1_ID, PORT_PIN_IN, STD_LOW, PORT_DIGITAL, PORT_MODE_GPIO, STD_OFF, STD_OFF, PORT_RESISTOR_OFF
  },
  {
   PortPin_C2_ID, PORT_PIN_IN, STD_LOW, PORT_DIGITAL, PORT_MODE_GPIO, STD_OFF, STD_OFF, PORT_RESISTOR_OFF
  },
  {
   PortPin_C3_ID, PORT_PIN_IN, STD_LOW, PORT_DIGITAL, PORT_MODE_GPIO, STD_OFF, STD_OFF, PORT_RESISTOR_OFF
  },
  {
   PortPin_C4_ID, PORT_PIN_IN, STD_LOW, PORT_DIGITAL, PORT_MODE_GPIO, STD_OFF, STD_OFF, PORT_RESISTOR_OFF
  },
  {
   PortPin_C5_ID, PORT_PIN_IN, STD_LOW, PORT_DIGITAL, PORT_MODE_GPIO, STD_OFF, STD_OFF, PORT_RESISTOR_OFF
  },
  {
   PortPin_C6_ID, PORT_PIN_IN, STD_LOW, PORT_DIGITAL, PORT_MODE_GPIO, STD_OFF, STD_OFF, PORT_RESISTOR_OFF
  },
  {
   PortPin_C7_ID, PORT_PIN_IN, STD_LOW, PORT_DIGITAL, PORT_MODE_GPIO, STD_OFF, STD_OFF, PORT_RESISTOR_OFF
  },
  {
   PortPin_D0_ID, PORT_PIN_IN, STD_LOW, PORT_DIGITAL, PORT_MODE_GPIO, STD_OFF, STD_OFF, PORT_RESISTOR_OFF
  },
  {
   PortPin_D1_ID, PORT_PIN_IN, STD_LOW, PORT_DIGITAL, PORT_MODE_GPIO, STD_OFF, STD_OFF, PORT_RESISTOR_OFF
  },
  {
   PortPin_D2_ID, PORT_PIN_IN, STD_LOW, PORT_DIGITAL, PORT_MODE_GPIO, STD_OFF, STD_OFF, PORT_RESISTOR_OFF
  },
  {
   PortPin_D3_ID, PORT_PIN_IN, STD_LOW, PORT_DIGITAL, PORT_MODE_GPIO, STD_OFF, STD_OFF, PORT_RESISTOR_OFF
  },
  {
   PortPin_D4_ID, PORT_PIN_IN, STD_LOW, PORT_DIGITAL, PORT_MODE_GPIO, STD_OFF, STD_OFF, PORT_RESISTOR_OFF
  },
  {
   PortPin_D5_ID, PORT_PIN_IN, STD_LOW, PORT_DIGITAL, PORT_MODE_GPIO, STD_OFF, STD_OFF, PORT_RESISTOR_OFF
  },
  {
   PortPin_D6_ID, PORT_PIN_IN, STD_LOW, PORT_DIGITAL, PORT_MODE_GPIO, STD_OFF, STD_OFF, PORT_RESISTOR_OFF
  },
  {
   PortPin_D7_ID, PORT_PIN_IN, STD_LOW, PORT_DIGITAL, PORT_MODE_GPIO, STD_OFF, STD_OFF, PORT_RESISTOR_OFF
  },
  {
   PortPin_E0_ID, PORT_PIN_IN, STD_LOW, PORT_DIGITAL, PORT_MODE_GPIO, STD_OFF, STD_OFF, PORT_RESISTOR_OFF
  },
  {
   PortPin_E1_ID, PORT_PIN_IN, STD_LOW, PORT_DIGITAL, PORT_MODE_GPIO, STD_OFF, STD_OFF, PORT_RESISTOR_OFF
  },
  {
   PortPin_E2_ID, PORT_PIN_IN, STD_LOW, PORT_DIGITAL, PORT_MODE_GPIO, STD_OFF, STD_OFF, PORT_RESISTOR_OFF
  },
  {
   PortPin_E3_ID, PORT_PIN_IN, STD_LOW, PORT_DIGITAL, PORT_MODE_GPIO, STD_OFF, STD_OFF, PORT_RESISTOR_OFF
  },
  {
   PortPin_E4_ID, PORT_PIN_IN, STD_LOW, PORT_DIGITAL, PORT_MODE_GPIO, STD_OFF, STD_OFF, PORT_RESISTOR_OFF
  },
  {
   PortPin_E5_ID, PORT_PIN_IN, STD_LOW, PORT_DIGITAL, PORT_MODE_GPIO, STD_OFF, STD_OFF, PORT_RESISTOR_OFF
  },
  {
   PortPin_F0_ID, PORT_PIN_IN, STD_LOW, PORT_DIGITAL, PORT_MODE_GPIO, STD_OFF, STD_OFF, PORT_RESISTOR_PULL_UP
  },
  {
   PortPin_F1_ID, PORT_PIN_OUT, STD_LOW, PORT_DIGITAL, PORT_MODE_GPIO, STD_OFF, STD_OFF, PORT_RESISTOR_OFF
  },
  {
   PortPin_F2_ID, PORT_PIN_OUT, STD_LOW, PORT_DIGITAL, PORT_MODE_GPIO, STD_OFF, STD_OFF, PORT_RESISTOR_OFF
  },
  {
   PortPin_F3_ID, PORT_PIN_OUT, STD_LOW, PORT_DIGITAL, PORT_MODE_GPIO, STD_OFF, STD_OFF, PORT_RESISTOR_OFF
  },
  {
   PortPin_F4_ID, PORT_PIN_IN, STD_LOW, PORT_DIGITAL, PORT_MODE_GPIO, STD_OFF, STD_OFF, PORT_RESISTOR_PULL_UP
  }

 }

};

